version: '3.8'
services:
  backend:
    build: ./backend
    container_name: health-backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - hive-metastore

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    platform: linux/amd64
    container_name: hive-metastore
    ports:
      - "9083:9083"
      - "10000:10000"
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
    depends_on:
      - hive-postgres

  hive-postgres:
    image: postgres
    container_name: hive-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
